app/urls.py
from django.urls import path, include
from app.views import AvtoViews, main, avto_haqida
 
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
   
    path('', main, name='avtolar'),
    path('all_avto', AvtoViews.as_view(), name='all_avto'),
    path('avto_haqida/<str:id>/', avto_haqida, name='avto_haqida'),
    path('posts/', main, name='posts')
]
 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
 

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views
from .forms import UserLoginForm

app_name = 'account'

urlpatterns = [
    path('register/', views.account_register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

templates/blog/admin.html
{% extends 'blog/main.html' %}

{% load static %}
{% block title %}
  Sardor Auto barchasi
{% endblock title %}
{% block content %}

<!-- <div  class="car">
    <div class="container">
       <div class="row">
          <div class="col-md-12">
             <div class="titlepage">

                <h2> {{ avto.nomi }} <span style="color:red">avtomobili haqida<span> </h2>
             </div>
          </div>
       </div>

       <div class="row">
             <center>
        <div class="col-md-4 padding_leri">
           <div class="car_box">
              <figure><img style="height: 250px;" src="{{ avto.rasm.url }}" alt="#"/></figure>
              <a href='/all_avto'><h3>{{ avto.nomi }}</h3></a>
              <h4>🏟 <b><span>Manzili</span>: {{ avto.manzil }}</h4>
              <h4>📆 <b><span>Yili:</span> {{ avto.yil }} - yil</h4>
              <h4>📊 <b><span>Probeg:</span> {{ avto.probeg }} km</h4>
              <h4>🛠 <b><span>Kuzov</span>: {{ avto.kuzov }}</h4>
              <h4>⛽ <b><span>Dvigatel:</span> {{ avto.dvigatel }}</h4>
              <h4>⚫ <b><span>Rangi:</span> {{ avto.rang }}</h4>
              <h4>💲 <b><span>Narxi :</span> {{ avto.narx }} so‘m</h4>
               <a href='tel: {{avto.tel_nomer}}'><b><span><h4>☎ Telefon nomer: {{ avto.tel_nomer }}</h4></a></span>
              <h4>📑 <b><span>Xarakteristika:</span> {{ avto.xarakteristika }}</h4>

               <a class="btn btn-warning" href="" role="button"><i class="fa file"> PDF format</a></i><br>
           </div>
           <br>
           <a class="btn btn-outline-danger" href="/all_avto" role="button"><i class="fa fa-angle-left">   Ortga</a></i>
         </center>
        </div>




       </div>
    </div>
 </div> -->
<style>
  th{
    border: style="border: 1px solid rgba(0, 0, 0, 0.374);";
  }
  td{
    border: style="border: 1px solid rgba(0, 0, 0, 0.374);";
  }
</style>

 <a class="btn btn-outline-danger" href="/all_avto" role="button"><i class="fa fa-angle-left"> Ortga </i> </a>
 <div class="center">
 <h2> {{ avto.nomi }} <span style="color:red">avtomobili haqida</span> </h2>

  <figure><img style="height: 220px;width:350px;" src="{{ avto.rasm.url }}" alt="#"/></figure>
 </div>

<table  class="table table-striped">

  <thead>
    <tr >
      <th  scope="col">1</th>
      <th   scope="col">Nomi</th>
      <th  scope="col">Manzili</th>
    </tr>
    <tr>
      <th   scope="row">1</th>
      <td  >{{ avto.nomi }}</td>
      <td  >{{ avto.manzil }}</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th   scope="col">2</th>
      <th   scope="col"> Yil</th>
      <th  scope="col">Probeg</th>
    </tr>

    <tr>
      <th   scope="row">2</th>
      <td  >{{ avto.yil }} - yil</td>
      <td  >{{ avto.probeg }} km</td>
    </tr>
    <tr>
     <th   scope="col">3</th>
     <th   scope="col">Kuzov</th>
     <th   scope="col">Dvigatel</th>
   </tr>
    <tr>
      <th   scope="row">3</th>
      <td  > {{ avto.kuzov }}</td>
      <td  >{{ avto.dvigatel }}</td>
    </tr>
    <tr>
     <th  scope="col">4</th>
     <th  scope="col">Rangi</th>
     <th   scope="col">Narxi</th>
   </tr>

   <tr>
    <th   scope="row">4</th>
    <td>{{ avto.rang }} rang</td>
    <td >{{ avto.narx }} so'm</td>
  </tr>

   <tr>
    <th   scope="col">5</th>
    <th   scope="col">Egasi ismi</th>
    <th   scope="col"> Bog'lanish</th>
  </tr>


   <tr>
    <th  scope="row">5</th>
    <td  >{{ avto.egasi }}</td>
    <a><td  >{{ avto.tel_nomer }}</td></a>


  </tr>

   <tr>
    <th   scope="col">6</th>
    <th   scope="col"> Ma'lumot</th>
    <th   scope="col">Yuklandi</th>


  </tr>

  <tr>
    <th   scope="row">6</th>

    <td >{{ avto.xarakteristika }} </td>
    <td >{{ avto.yuklangan_sana }} </td>


  </tr>
  </tbody>


</table><br>



 <a class="btn btn-warning" href="" role="button" onclick="window.print()"><i class="fa file"> PDF format</i></a>
 {% endblock content %}




<script>
  //Get the button
let mybutton = document.getElementById("btn-back-to-top");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function () {
 scrollFunction();
};

function scrollFunction() {
 if (
   document.body.scrollTop > 20 ||
   document.documentElement.scrollTop > 20
 ) {
   mybutton.style.display = "block";
 } else {
   mybutton.style.display = "none";
 }
}
// When the user clicks on the button, scroll to the top of the document
mybutton.addEventListener("click", backToTop);

function backToTop() {
 document.body.scrollTop = 0;
 document.documentElement.scrollTop = 0;
}
</script>
<style>
  #btn-back-to-top {
     position: fixed;
     bottom: 20px;
     right: 20px;
     display: none;
   }
</style>
<button
       type="button"
       class="btn btn-danger btn-floating btn-lg"
       id="btn-back-to-top"
       >
 <i class="fas fa-arrow-up"></i>
</button>

templates/blog/avto_batafsil.html
{% extends 'blog/main.html' %}

{% load static %}
{% block title %}
    Sardor Auto barchasi
{% endblock title %}
{% block content %}

<style>
    * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }

    body {
        font-family: Verdana, sans-serif;
    }




    /* Caption text */
    .text {
        color: black;
        font-size: 15px;
        padding: 8px 12px;
        position: absolute;
        bottom: 8px;
    
        text-align: center;
    }

    /* Number text (1/3 etc) */
    .numbertext {
        color: #000000;
        font-size: 12px;
        padding: 8px 12px;
        position: absolute;
        top: 0;
    }


    .tablisa  th {
        font-family: Roboto, 'Segoe UI', Tahoma, sans-serif;
        font-size: 30px;
    }

    .tablisa  td {
        font-family: Roboto, 'Segoe UI', Tahoma, sans-serif;
        font-size:30px;  
    }
    .umumiy{
        margin-top: 0px;
       }
    @media only screen and (max-width: 600px) {
        .tablisa  td {
            font-family: Roboto, 'Segoe UI', Tahoma, sans-serif;
        font-size: 20px;  
        letter-spacing: -1.3px;
    }
    .big__div__title{
        font-family: Roboto, 'Segoe UI', Tahoma, sans-serif;
        font-size: 20px;  
    }
    .tablisa  th {
        font-family: Roboto, 'Segoe UI', Tahoma, sans-serif;
        font-size: 20px;
        letter-spacing: -1.1px;
    }
    }
    .image__fluid{
        display: flex;
        justify-content: center;
    }
    .image__fluid img{
        width: 30%;
        max-width: 30%;
        height: auto;
        object-fit: contain;
        object-position: center;
        border: none;
    }
    tr{
        border-bottom: 1px solid black;
    }
   .big__div{
    border: 1px solid black;
    margin-top: 10%;
   }
   
</style><center>
    <div class="umumiy">
<div style="width:95%" class="big__div">
    <h2 class="big__div__title" style="font-size: 30px; text-align: center;"> {{ avto.nomi }} <span style="color:red; font-size: 30px;">avtomobili haqida</span></h2>
            <div class="image__fluid">
                            <img src="{{ avto.rasm.url }}" class="d-block w-500 " alt="...">
            </div>

                <table class="table table-bordered tablisa mt-2">
                    <tr>
                        <th  scope="col">1</th>
                        <th  scope="col">Nomi</th>
                        <th  scope="col">Manzili</th>
                    </tr>
                    <tr>
                        <th  scope="row"></th>
                        <td >{{ avto.nomi }}</td>
                        <td >{{ avto.manzil }}</td>
                    </tr>
                    <tr>
                        <th  scope="col">2</th>
                        <th  scope="col"> Yil</th>
                        <th scope="col">Probeg</th>
                    </tr>

                    <tr>
                        <th  scope="row"></th>
                        <td>{{ avto.yil }} - yil</td>
                        <td>{{ avto.probeg }} km</td>
                    </tr>
                    <tr>
                        <th  scope="col">3</th>
                        <th  scope="col">Kuzov</th>
                        <th  scope="col">Dvigatel</th>
                    </tr>
                    <tr>
                        <th  scope="row"></th>
                        <td > {{ avto.kuzov }}</td>
                        <td >{{ avto.dvigatel }}</td>
                    </tr>
                    <tr>
                        <th  scope="col">4</th>
                        <th  scope="col">Rangi</th>
                        <th  scope="col">Narxi</th>
                    </tr>

                    <tr>
                        <th  scope="row"></th>
                        <td >{{ avto.rang }} rang</td>
                        <td >{{ avto.narx }} so'm</td>
                    </tr>
                    <tr>
                        <th  scope="col">5</th>
                        <th  scope="col">️Egasi ismi</th>
                        <th  scope="col">Bog'lanish</th>
                    </tr>
                    <tr>
                        <th  scope="row"></th>
                        <td >{{ avto.egasi }}</td>
                        <a>
                            <td >{{ avto.tel_nomer }}</td>
                        </a>
                    </tr>
                    <tr>
                        <th  scope="col">6</th>
                        <th  scope="col"> Ma'lumot</th>
                        <th  scope="col">Yuklandi</th>
                    </tr>
                    <tr>
                        <th  scope="row"></th>
                        <td>{{ avto.xarakteristika }} </td>
                        <td >{{ avto.yuklangan_sana }} </td>
                    </tr>
                </table>
            </center>
        <br>
    
        <div style="text-align: center;">
            <u><h1 href="avtoprodaj.uz" style="font-size:30px;">Avtoprodaj.uz</h1></u>
            <h3  style="font-size:30px; color:red ">+998996658575</h3>
    </div>
    {% if request.user.is_superuser %}
        <div class="d-flex justify-content-center">
            <div style="font-size:20px; border-radius:10px" class="btn btn-warning " href="" id="pdf"
                 role="button"
                 onclick="document.getElementById('pdf').style.display = 'none',
           document.getElementById('pdf').classList.add('text-white'),window.print()">
                PDF format
            </div>
        </div><br><br><br><br>

</div>
</div>  
    {% endif %}
{% endblock content %}

<!-- tepaga chiqish tugmasi -->


<script>
    //Get the button
    let mybutton = document.getElementById("btn-back-to-top");

    // When the user scrolls down 20px from the top of the document, show the button

    function myFunction() {
        let a = document.getElementsByClassName('pdf')
        for (let i = 0; i < a.length; i++) {
            console.log(a[i])
        }


    }

    window.onscroll = function () {
        scrollFunction();
    };

    function scrollFunction() {
        if (
            document.body.scrollTop > 20 ||
            document.documentElement.scrollTop > 20
        ) {
            mybutton.style.display = "block";
        } else {
            mybutton.style.display = "none";
        }
    }

    // When the user clicks on the button, scroll to the top of the document
    mybutton.addEventListener("click", backToTop);

    function backToTop() {
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
    }


</script>
<style>
    #btn-back-to-top {
        position: fixed;
        bottom: 20px;
        right: 20px;
        display: none;
    }
</style>
<button type="button"
        class="btn btn-danger btn-floating btn-lg"
        id="btn-back-to-top">
    <i class="fas fa-arrow-up"></i>
</button>

templates/blog/avtolar.html
{% extends 'blog/main.html' %}

{% load static %}
{% block title %}
    Barcha avtomobillar
{% endblock title %}
{% block content %}


    <!--All Categories-->

    <style>
        body {
          font-family: Arial;
        }

        * {
          box-sizing: border-box;
        }
        form.example{
            display: flex;
            justify-content: center;
        }
        form.example input[type=text] {
          border-radius: 16px;
          font-size: 17px;
          border: 1px solid grey;
          float: left;
          background: #f1f1f1;
          margin-right: 5px;
          padding: 3px 3px;
        }

        form.example button {
          border-radius: 16px;
          padding: 10px 20px;
          background: #2196F3;
          color: white;
          font-size: 17px;
          border: 1px solid grey;
          border-left: none;
          cursor: pointer;
        }

        form.example button:hover {
          background: #0b7dda;
        }

        form.example::after {
          content: "";
          clear: both;
          display: table;
        }
        .center{
            margin-bottom: 200px;
        }
        .card{
            width: 240px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }
        .card-img-top{
            width:250px!important ;
            height: 200px!important;
        }
        .card__btn{
            padding: 8px 20px;
        }
        .card-body{
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .card__container{
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .titlepage{
            margin-bottom: 15px;
        }
        .titlepage h2{
            font-size: 20px;
            letter-spacing: 1.5px;
            line-height: 25px;
            margin: 0;
        }
        </style>
        <form class="example" method="POST" action="{% url 'posts' %}">
            {% csrf_token %}
            <input  type="text" placeholder="🔎 Qidiruv.." title="qidiruv" name="qidiruv">
            <button type="submit"><i class="fa fa-search"></i></button>
          </form>

{% comment %}
    <form class="d-flex" method="POST" action="{% url 'posts' %}">
        {% csrf_token %}
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="🔎 Qidiruv.." title="qidiruv" name="qidiruv">
    </form> {% endcomment %}

    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>


    <div class="car">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="titlepage">
                        <h2> Barcha Avtomobillar </h2>
                    </div>
                </div>
            </div>
       <div class="center">
            <div style="border-radius: 2px!important;" class="row">

                {% for avto in all_avto %}
                    <div class="col-12 col-sm-6 col-md-4 col-lg-3 mt-3 card__container" >
                        <div class="card">
                            <img style="width: 100%;"  src="{{ avto.rasm.url }}" class="card-img-top" class="d-block w-500 "  alt="...">
                        <div class="card-body">
                            <h6 style="text-align:center;font-weight: bolder;"class="card-title">{{ avto.nomi }}</h6>
                            <p style="text-align:center;font-weight:bolder; font-size: 10px;"
                               class="card-title">{{ avto.narx }} so'm</p>
                            <p style="text-align: center; font-size: 9px;" class="card-title">{{ avto.manzil }}</p>
                            <a  href="{% url 'avto_haqida' avto.id %}" class="btn btn-primary card__btn">Batafsil</a>
                        </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
        <div class="center-2">
        <!--This is pagination-->
            {% if page_obj.has_other_pages %}
                <div class="text-right">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1">&laquo;</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&#8249;</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    {{ page_obj.previous_page_number }}
                                </a>
                            </li>
                        {% endif %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ page_obj.number }}">
                                {{ page_obj.number }}
                            </a>
                        </li>
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="?page={{ page_obj.next_page_number }}">
                                    {{ page_obj.next_page_number }}
                                </a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&#8250;</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
    </div>
</div>
{% endblock content %}



{% if queryset.has_other_pages %}
    <div class="pagination">
        <ul class="container">

            {% if queryset.has_previous %}
                <li><a href="?page={{ queryset.previous_page_number }}" class="btn page-link"
                       data-page="{{ queryset.previous_page_number }}">&#10094; Prev</a></li>
            {% endif %}


            {% for page in custom_range %}

                {% if page == queryset.number %}
                    <li><a href="?page={{ page }}" class="btn page-link btn--sub" data-page="{{ page }}">{{ page }}</a>
                    </li>
                {% else %}
                    <li><a href="?page={{ page }}" class="btn page-link" data-page="{{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}

            {% if queryset.has_next %}
                <li><a href="?page={{ queryset.next_page_number }}" class="btn page-link"
                       data-page="{{ queryset.next_page_number }}">Next &#10095;</a></li>
            {% endif %}


        </ul>
    </div>
{% endif %}



<script src="{% static 'js/top.js' %}"></script>

templates/blog/login.html
{% extends './sub_base.html' %}
{% block title %} Kirish {% endblock %}
{% block content %}
    <div class="container">
      <div class="login d-flex align-items-center">
        <div class="col-12 col-md-12 col-lg-12 mx-auto">
          <div class="col-md-6 mx-auto">
            <form class="account-form" action="{% url 'account:login' %}" method="post">
                {% csrf_token %}
                <h3 class="mb-4 center"><p align="center">Kirish</p></h3>
                {% if form.errors %}
                <div class="alert alert-primary" role="alert">
                  Xatolik: Email yoki parol xato!
                </div>
                {% endif %}
                <label class="form-label">{{ form.username.label}}</label>
                {{ form.username}}
                <label class="form-label">{{ form.password.label}}</label>
                {{ form.password}}
                <div class="d-grid gap-2">
                  <input type="hidden" name="next" value="{{ next }}">
                  <button class="btn btn-primary py-2 mb-4 mt-5 fw-bold" type="submit" value="Log-in">Kirish
                  </button>
                </div>
                <div class="flex-column justify-content-center mx-auto pb-3">
                  <div class="text-center"><a href="{% url "account:register" %}">Yangi akkaunt yaratish</a></div>
                </div>
              </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/blog/pagination.html
{% if queryset.has_other_pages %}
<div class="pagination">
    <ul class="container">

        {% if queryset.has_previous %}
        <li><a href="?page={{queryset.previous_page_number}}" class="btn page-link"
                data-page="{{queryset.previous_page_number}}">&#10094; Prev</a></li>
        {% endif %}


        {% for page in custom_range %}

        {% if page == queryset.number%}
        <li><a href="?page={{page}}" class="btn page-link btn--sub" data-page="{{page}}">{{page}}</a></li>
        {% else %}
        <li><a href="?page={{page}}" class="btn page-link" data-page="{{page}}">{{page}}</a></li>
        {% endif %}
        {% endfor %}

        {% if queryset.has_next %}
        <li><a href="?page={{queryset.next_page_number}}" class="btn page-link"
                data-page="{{queryset.next_page_number}}">Next &#10095;</a></li>
        {% endif %}



    </ul>
</div>
{% endif %}

templates/blog/registration.html
{% extends './sub_base.html' %}
{% block title %}Ro'yhatdan o'tish{% endblock %}
{% block content %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7 mx-auto">
                            <form class="account-form p-4 rounded col-lg-16 mx-auto" action="." method="post">
                                {% csrf_token %}
                                <h3 class="mb-2"> Akkaunt yaratish</h3>
                                {% if form.errors %}
                                <p>Iltimos quyidagi xatoliklarni to'g'irlang</p>
                                {% for field in form %}
                                {% if field.errors %}
                                <div class="alert alert-primary" role="alert">
                                    {{ field.label }}: {{ field.errors|striptags }}
                                </div>

                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                <label>{{ form.email.label }}<small class="text-muted small">
                                        (Majburiy)</small></label>
                                {{ form.email }}
                                <label>{{ form.password.label }}<span class="text-muted mb-4">
                                        (Majburiy)</span></label>
                                {{ form.password }}
                                <label>{{ form.password2.label }}<span class="text-muted small">
                                        (Majburiy)</span></label>
                                {{ form.password2 }}
                                <button class="btn btn-primary btn-block py-2 mb4 mt-5 fw500 w-100" type="submit">Ro'yhatdan o'tish</button>
                                <p class="text-center">
                                    <a href="{% url 'account:login' %}">Agar ro'yhatdan o'tgan bo'lsangiz bu yerga bosing</a>
                                </p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/result.html
{% extends 'blog/main.html' %}

{% load static %}
{% block title %}
    Sardor Auto barchasi
{% endblock title %}
{% block content %}

    <div class="car" style="display: flex">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="titlepage">

                        <h2> {{ avto.nomi }} <span style="color:red">avtomobili haqida</span></h2>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-7">
                        <div class="">
                            <figure><img style="height: 250px;" src="{{ avto.rasm.url }}" alt="#"/></figure>
                            <a href='/all_avto'><h3>{{ avto.nomi }}</h3></a>
                            <h4>🏟 </b><span>Manzili</span>: {{ avto.manzil }}</h4>
                            <h4>📆 </b><span>Yili:</span> {{ avto.yil }} - yil</h4>
                            <h4>📊 </b><span>Probeg:</span> {{ avto.probeg }} km</h4>
                            <h4>🛠 </b><span>Kuzov</span>: {{ avto.kuzov }}</h4>
                            <h4>⛽ </b><span>Dvigatel:</span> {{ avto.dvigatel }}</h4>
                            <h4>⚫ </b><span>Rangi:</span> {{ avto.rang }}</h4>
                            <h4>💲 </b><span>Narxi :</span> {{ avto.narx }} so‘m</h4>
                            <a href='tel: {{ avto.tel_nomer }}'></b><span><h4>☎ Telefon nomer: {{ avto.tel_nomer }}</h4></span></a>
                            <h4>📑 </b><span>Xarakteristika:</span> {{ avto.xarakteristika }}</h4>
                            <!--pdf uchun-->
                            <a class="btn btn-warning" href="" role="button"><i class="fa file"> PDF
                                format </i></a></br>
                        </div>
                        <br>
                        <a class="btn btn-outline-danger" href="/all_avto" role="button"><i class="fa fa-angle-left">Ortga</i></a>
                    </div>
                </div>
            </div>

{#            <div class="row">#}
{#                <center>#}
{#                    <div class="col-md-4 padding_leri">#}
{#                        <div class="car_box">#}
{#                            <figure><img style="height: 250px;" src="{{ avto.rasm.url }}" alt="#"/></figure>#}
{#                            <a href='/all_avto'><h3>{{ avto.nomi }}</h3></a>#}
{#                            <h4>🏟 </b><span>Manzili</span>: {{ avto.manzil }}</h4>#}
{#                            <h4>📆 </b><span>Yili:</span> {{ avto.yil }} - yil</h4>#}
{#                            <h4>📊 </b><span>Probeg:</span> {{ avto.probeg }} km</h4>#}
{#                            <h4>🛠 </b><span>Kuzov</span>: {{ avto.kuzov }}</h4>#}
{#                            <h4>⛽ </b><span>Dvigatel:</span> {{ avto.dvigatel }}</h4>#}
{#                            <h4>⚫ </b><span>Rangi:</span> {{ avto.rang }}</h4>#}
{#                            <h4>💲 </b><span>Narxi :</span> {{ avto.narx }} so‘m</h4>#}
{#                            <a href='tel: {{ avto.tel_nomer }}'></b><span><h4>☎ Telefon nomer: {{ avto.tel_nomer }}</h4></span></a>#}
{#                            <h4>📑 </b><span>Xarakteristika:</span> {{ avto.xarakteristika }}</h4>#}
{#                            <!--pdf uchun-->#}
{#                            <a class="btn btn-warning" href="" role="button"><i class="fa file"> PDF#}
{#                                format </i></a></br>#}
{#                        </div>#}
{#                        <br>#}
{#                        <a class="btn btn-outline-danger" href="/all_avto" role="button"><i class="fa fa-angle-left">Ortga</i></a>#}
{#                    </div>#}
{#                </center>#}
{#            </div>#}


        </div>
    </div>
    </div>

{% endblock content %}

templates/blog/search.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    span {
        color: red;
    }
</style>
{% extends 'blog/basic.html' %}
{% block title %}
    Qidiruv | {{ block.super }}
{% endblock title %}
{% block content %}<center>
    <div class="row sm-3">
        {% for post in posts %}
        
            <div class="col-sm-3 mt-5">
                <div class="card">
                    <img style="height: 250px!important;" src="{{ post.rasm.url }}" class="card-img-top" alt="...">
                    <div>
                        <div class="card-body">
                            <h6 style="text-align:center;font-weight:bolder" class="card-title">{{ post.nomi }}</h6>
                            <p style="text-align:center;font-weight:bolder; font-size: 10px;"
                               class="card-title">{{ post.narx }} so'm</p>
                            <p style="text-align:center;font-size: 9px;" class="card-title">{{ post.manzil }}</p>
                            <a style="width:100%;" href="{% url 'avto_haqida' post.id %}" class="btn btn-primary">Batafsil </a>
                        </div>
                    </div>
                </div>
            </div>
          </center>
        {% endfor %}
{% endblock content %}

<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>